config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :category do
    resources :theme do
      resources :comment
    end
  end
  root 'category#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :themes , dependent: :delete_all
  validates :title , presence: true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :theme
  validates :title ,:content, presence: true
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :comments , dependent: :delete_all
  belongs_to :category
  validates :title ,:content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def new
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    @categories = Category.all
    if @category.save
      #redirect_to :action => 'show' ,:id => @category.id
      redirect_to :action =>'new'
    else
      render 'new'
    end
  end

  def show
    @category= Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id]);
    @titulo = @category.title
  end
  
  def update
    @category = Category.find(params[:id])
    @category.update_attributes(category_params)
    redirect_to :action => 'edit'
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to :action => 'new' 
  end
  
  private 
  def category_params
    params.require(:category).permit(:title)  
  end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :load_id
  def new
    @comments = @theme.comments.all
    @comment = @theme.comments.new
  end
  def create
    @comment = @theme.comments.new(comment_params)
    @comments = @theme.comments.all
    if @comment.save
      redirect_to :action => 'new'
    else
      render 'new'
    end
    #@comment.save
    #redirect_to :action => 'new'
  end

  def edit
    @comment = @theme.comments.find(params[:id])
    @titulo = @comment.title
    @content = @comment.content
  end

  def update
    @comment =@theme.comments.find(params[:id])
    @comment.update_attributes(comment_params)
    redirect_to :action => 'edit'
  end


  def show
  end

  private
  def comment_params
     params.require(:comment).permit(:title,:theme_id,:content)
  end
  def load_id
    @theme = Theme.find(params[:theme_id])
  end
end

app/controllers/theme_controller.rb
class ThemeController < ApplicationController
  before_action :log
  def new
    @themes=@category.themes.all
    @theme=@category.themes.new
  end
  def create
    @theme = @category.themes.new(theme_params)
    @themes = @category.themes.all
    if @theme.save
      redirect_to :action => 'new'
    else
      render 'new'
    end
    #@theme.save
    #redirect_to :action => 'new' 
  end

  def edit
    @theme = @category.themes.find(params[:id]);
    @titulo = @theme.title
    @content = @theme.content
  end

  def update
    @theme = @category.themes.find(params[:id])
    @theme.update_attributes(theme_params)
    redirect_to :action => 'edit'
  end

  def destroy
    @theme = @category.themes.find(params[:id])
    @theme.destroy
    redirect_to :action => 'new'
  end
  
  def show
    @theme = @category.themes.find(params[:id])
  end

  private
  def theme_params
    params.require(:theme).permit(:title,:category_id,:content)
  end

  def log
    @category=Category.find(params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/views/category/edit.html.erb
<h1>Category#edit</h1>
<p>Find me in app/views/category/edit.html.erb</p>

<%= form_for @category , :url => { :action => :update   }  , :method => :put do |f| %>

<!-- Campos -->
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title , { :value => @category.title } %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/category/new.html.erb
<h1>Category#new</h1>
<h1> <%= link_to 'Category', new_category_path %> > </h1>
<%= form_for (@category),:url => { :action => :create }   do |f| %> 
<!-- Mensajes de error -->
<% if @category.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited
        this post from being saved:</h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
       <% end %>
      </ul>
    </div>
  <% end %>
<!-- Campos -->
   <p> 
      <%= f.label :title, "Título" %>
      <br />
      <%= f.cktext_area :title  %>
   </p>
   <p> 
         <%= f.submit "Enviar" %> 
   </p>
<%end %>

<p>Listando Content</p>
<% @categories.each do |i| %>
<p>Title : <%= i.title %></p>
|<%= link_to "show " , new_category_theme_path(i.id)  %>
|<%= link_to "Edit", edit_category_path(i.id) %>
|<%= link_to "Eliminar" , { :action => :destroy, :id => (i.id) }, :method => :delete  %>
<% end %>

app/views/category/show.html.erb
<h1>Category#show</h1>
<p>Find me in app/views/category/show.html.erb</p>
<%= @category.title %>

app/views/comment/edit.html.erb
<h1>Comment#edit</h1>
<p>Find me in app/views/comment/edit.html.erb</p>

<p>Find me in app/views/theme/edit.html.erb</p>
<%= form_for @comment , :url => { :action => :update }  , :method => :put do |f| %>
  <!-- Mensajes de error -->

<!-- Campos -->
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title , { :value => @comment.title } %>
  </p>
    <p>
    <%= f.label :content %><br>
    <%= f.text_field :content , { :value => @comment.content } %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comment/new.html.erb
<h1>Comment#new</h1>
<p>Find me in app/views/comment/new.html.erb</p>
<p>especificando el tema </p>
<%= @theme.title %>
<p>
  
<%= @theme.content %>
</p>

<center>  
<p>Add a comment</p>
<%= form_for ([@theme,@comment]),:url => { :action => :create }   do |f| %> 
<!-- Mensajes de error -->
<% if @comment.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited
        this post from being saved:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
       <% end %>
      </ul>
    </div>
  <% end %>
<!-- Campos -->
   <p> 
      <%= f.label :title, "Título" %>
      <br />
      <%= f.text_field :title  %>
   </p>
   <p> 
      <%= f.label :content, "Contenido" %>
      <br />
      <%= f.cktext_area :content  %>
   </p>
   <p> 
      <%= f.submit "Enviar" %> 
   </p>
<%end %>
</center>
<h3>Listando los comentarios de este tema</h3>
<% @comments.each do |i|%>
<p><%= i.title %></p>
<p><%= raw i.content %></p>
<p><%= @theme.category_id %></p>    
|show
|<%= link_to 'edit', edit_category_theme_comment_path( i.theme_id , @theme.category_id , i.id )%>
|delete
<%end%>

app/views/comment/show.html.erb
<h1>Comment#show</h1>
<p>Find me in app/views/comment/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduCate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/theme/edit.html.erb
<h1>Theme#edit</h1>
<p>Find me in app/views/theme/edit.html.erb</p>
<%= form_for @theme , :url => { :action => :update }  , :method => :put do |f| %>
  <!-- Mensajes de error -->

<!-- Campos -->
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title , { :value => @theme.title } %>
  </p>
    <p>
    <%= f.label :content %><br>
    <%= f.text_field :content , { :value => @theme.content } %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/theme/new.html.erb
<p>Category  <%= @category.title %> </p>


<p>Add theme for category</p>
<h1> <%= link_to 'Category', new_category_path %> > </h1>
<%= form_for ([@category,@theme]),:url => { :action => :create }   do |f| %> 
<!-- Mensajes de error -->
<% if @theme.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@theme.errors.count, "error") %> prohibited
        this post from being saved:</h2>
      <ul>
        <% @theme.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
       <% end %>
      </ul>
    </div>
  <% end %>
<!-- Campos -->
   <p> 
      <%= f.label :title, "Título" %>
      <br />
      <%= f.text_field :title  %>
   </p>
   <p> 
      <%= f.label :content, "Contenido" %>
      <br />
      <%= f.cktext_area  :content  %>
   </p>
   <p> 
         <%= f.submit "Enviar" %> 
   </p>
<%end %>


<center>
  <p>Themes</p>
  <% @themes.each do |item| %>
  <p>Title: <%= item.title %></p>
  <p>Content: <%= raw item.content %></p>
  |<%= link_to "show", new_category_theme_comment_path( item.category_id, :theme_id =>  item.id )%>
  |<%= link_to "edit", edit_category_theme_path(item.category_id , item.id) %>
  |<%= link_to "Eliminar" , { :action => :destroy, :id => (item.id) }, :method => :delete  %>
  <% end %>
  
</center>

app/views/theme/show.html.erb
<h1>Theme#show</h1>
<p>Find me in app/views/theme/show.html.erb</p>